version: '3.8'

services:
  sapp1:
   image: docker.io/library/cache-standalone
   ports:
     - "8080:8080"
   links:
     - redis

  sapp2:
   image: docker.io/library/cache-standalone
   ports:
     - "9080:8080"
   links:
     - redis

  redis:
   image: "redis"
   ports:
     - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: mysqlStandAlone
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"   