version: '3.8'

services:
  app1:
    image: docker.io/library/cache-local
    ports:
      - "8080:8080"
      
  app2:
    image: docker.io/library/cache-local
    ports:
      - "9080:8080"

  mysql:
    image: mysql:8.0
    container_name: mysqlLocal
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"