version: '3.8'

services:
  app1:
    image: docker.io/library/cache-read-write-through
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/productDb
    links:
      - mysql
  app2:
    image: docker.io/library/cache-read-write-through
    ports:
      - "9080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/productDb
    links:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"